### ISSUE TITLE
Request for feedback

### ISSUE THREAD

**Issue by kbarnhart** [TerrainBento/terrainbento#25]
@cmshobe @gregtucker @Glader011235 

Please take a look at the docstrings/general level of testing in terrainbento/master

Read The Docs is not currently building, I don't know why. I don't want this to hold up getting feedback and moving forward this week.

Look at the following files:

`base_class/erosion_model.py`
`base_class/stochastic_erosion_model.py`
`boundary_condition_handlers/` all of them
`derived_models/model_000_basic.py`
`model_template/model_template.py`

Some general questions:
1) clarity of description
2) sadly... spelling/grammar
3) Bold/pre-formatted/italic notation. consistent and helpful?

Note also that I'm partway through transitioning from the old variable names to the new variable names...

**Comment by cmshobe** [comment]
These look awesome! I think the various formatting and emphasis touches are very helpful. I submitted a PR (#27) with minor typo and grammar corrections.

The one larger comment I have is that in the BC handler "noise_adder.py," most of the documentation was (accidentally?) copy+pasted over from the capture handler. May want to take another look at that one. Otherwise all looks good!

**Comment by kbarnhart** [comment]
@Glader011235 hold off on this for a moment. Let me do some updates and merging first. I think that it should be all ready by Monday though.

**Comment by kbarnhart** [comment]
@Glader011235 have at it now. 

thanks!
