### ISSUE TITLE
002 test errors

### ISSUE THREAD

**Issue by kbarnhart** [TerrainBento/terrainbento#60]
looking at the steady state notebooks, it appears that model 002 does not have a true analytical solution but should be falling into a range. 

the tests do not reflect that. 

Also, model program 002 implements 002 and 006 (BasicSsTh), and did not reflect the two programs.

**Comment by cmshobe** [comment]
Yeah fair point; I just made the threshold low enough and the test decimal precision coarse enough that the threshold case would pass an is-almost-equal test. Your new test looks way better. 

The reason I had had m=1/3, n=1 instead of n=2/3 for the shear stress test is that something broke in the SmoothThresholdEroder iterative solver when n wasn't equal to zero. I don't know more than that but that's where I'd go to chase it down.
